title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://lawtlee.github.io/just-the-docs

aux_links:
  Template Repository: https://github.com/lawtlee/just-the-docs
